LightningAssignment/force-app/main/default/objects/Car_Maker__c/Car_Maker__c.object-meta.xml
<CustomObject>
    <label>Car Maker</label>
    <nameField>
        <label>Car Maker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Makers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LightningAssignment/force-app/main/default/objects/Car_Maker__c/fields/Founded__c.field-meta.xml
<CustomField>
    <fullName>Founded__c</fullName>
    <label>Founded</label>
    <type>Date</type>
</CustomField>

LightningAssignment/force-app/main/default/objects/Car_Maker__c/fields/Founder__c.field-meta.xml
<CustomField>
    <fullName>Founder__c</fullName>
    <label>Founder</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

LightningAssignment/force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LightningAssignment/force-app/main/default/objects/Model__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>City car</fullName>
            </value>
            <value>
                <fullName>Subcompact car</fullName>
            </value>
            <value>
                <fullName>Compact car</fullName>
            </value>
            <value>
                <fullName>Mid-size car</fullName>
            </value>
            <value>
                <fullName>Entry-level luxury car</fullName>
            </value>
            <value>
                <fullName>Full-size car</fullName>
            </value>
            <value>
                <fullName>Mid-size luxury car</fullName>
            </value>
            <value>
                <fullName>Full-size luxury</fullName>
            </value>
            <value>
                <fullName>Personal luxury car</fullName>
            </value>
            <value>
                <fullName>Grand tourer</fullName>
            </value>
            <value>
                <fullName>Supercar</fullName>
            </value>
            <value>
                <fullName>Convertible</fullName>
            </value>
            <value>
                <fullName>Roadster</fullName>
            </value>
            <value>
                <fullName>Mini MPV</fullName>
            </value>
            <value>
                <fullName>Compact MPV</fullName>
            </value>
            <value>
                <fullName>Minivan</fullName>
            </value>
            <value>
                <fullName>Subcompact SUV</fullName>
            </value>
            <value>
                <fullName>Compact SUV</fullName>
            </value>
            <value>
                <fullName>Mid-size SUV</fullName>
            </value>
            <value>
                <fullName>Full-size SUV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LightningAssignment/force-app/main/default/objects/Model__c/fields/Horsepower__c.field-meta.xml
<CustomField>
    <fullName>Horsepower__c</fullName>
    <label>Horsepower</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LightningAssignment/force-app/main/default/objects/Model__c/fields/Maker__c.field-meta.xml
<CustomField>
    <fullName>Maker__c</fullName>
    <label>Maker</label>
    <referenceTo>Car_Maker__c</referenceTo>
    <relationshipLabel>Models</relationshipLabel>
    <relationshipName>Models</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LightningAssignment/force-app/main/default/objects/Model__c/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

LightningAssignment/force-app/main/default/classes/CarMakerController.cls
public with sharing class CarMakerController {
    
    @AuraEnabled(cacheable=true)
    public static List<Car_Maker__c> getCarMakerList(){
        return [SELECT id, Name, Founded__c, Founder__c, Number_of_employees__c, Website__c FROM Car_Maker__c ORDER BY CreatedDate DESC LIMIT 10];       
    }

    @AuraEnabled(cacheable=true)
    public static List<Model__c> getCarModelList(id makerId){
        return [SELECT id, Name, Class__c, Horsepower__c, MPG__c, Price__c FROM Model__c WHERE Maker__c =: makerId LIMIT 10];
    }
}